### ISSUE TITLE
.look_at

### ISSUE THREAD

**Issue by ghost** [kidscancode/3d_spaceship_demo#1]
I feel more comfortable without the flip of the camera when I execute a 1/2 loop, for example. So I set in Space.gd,

```
func _process(delta):
	$ChaseCamera.look_at($ExecutionerKB.transform.origin, Vector3.ZERO)
```

instead of the default **Vector3.UP**. However each frame the Debugger types,

> E 0:00:02.230   look_at_from_position: Up vector and direction between node origin and target are aligned, look_at() failed.
>   <C++ Error>   Condition "p_up.cross(p_target - p_pos) == Vector3()" is true.
>   <C++ Source>  scene/3d/spatial.cpp:691 @ look_at_from_position()
>   <Stack Trace> Space.gd:11 @ _process()

**Comment by cbscribe** [comment]
`look_at()` requires an "up" vector. This is the axis around which the object will rotate first to align with the target.

(0, 0) is not a direction, so you're not giving it an axis to rotate around.

**Comment by ghost** [comment]
There is any way to overcome this error without touching in C++? Have you tried playing with Vector3.ZERO? I followed another tutorial of yours and set the mouse axis as input,

```
func _input(mouse_controls):
	# X axis controlling ROLL,
	if mouse_controls is InputEventMouseMotion:
		if mouse_controls.relative.x > 0:
			rotate_object_local(Vector3.BACK, -lerp(0, spin, mouse_controls.relative.x/10))
			transform.basis = transform.basis.orthonormalized()
		elif mouse_controls.relative.x < 0:
			rotate_object_local(Vector3.BACK, -lerp(0, spin, mouse_controls.relative.x/10))
	# inverted Y axis controlling PITCH,
	if mouse_controls is InputEventMouseMotion:
		if mouse_controls.relative.y > 0:
			rotate_object_local(Vector3.LEFT, -lerp(0, spin, mouse_controls.relative.y/10))
			transform.basis = transform.basis.orthonormalized()
		elif mouse_controls.relative.y < 0:
			rotate_object_local(Vector3.LEFT, -lerp(0, spin, mouse_controls.relative.y/10))
```

However, due to the sensibility being high, some acrobatics maneuvers are a bit difficult because the camera displacement. Whatsoever, many thanks for the tutorial :)

**Comment by cbscribe** [comment]
It's not an error to "overcome". You can't rotate a body to look at a position without specifying an axis to rotate around. It doesn't make sense, physically or mathematically.

This tutorial is not really about camera tracking, but there are lots of ways you can do this, assuming you want to stick with a fixed camera and not have a chase camera instead. For example, you could try using the ship's up vector instead of the global up vector to keep the camera aligned with the ship.
